### ISSUE TITLE
Unexpected failure when parsing test results from stable Dart SDK

### ISSUE THREAD

**Issue by aaronlademann-wf** [dorny/test-reporter#113]
Hi there!

I noticed today that the following line is possible in `test-results.json` within a Dart unit test results output:

```jsonl
{"testID":1,"messageType":"print","message":"Consider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'pub run test --chain-stack-traces'.","type":"print","time":65561}
```

The presence of this line - specifically - a line with `"messageType":"print"` causes this action to throw:

```
Error: Cannot read property 'print' of undefined
```

<img width="618" alt="Screen Shot 2021-05-12 at 2 20 56 PM" src="https://user-images.githubusercontent.com/1750797/118045892-61c2f900-b32d-11eb-90e3-a5e208c9d3e4.png">

---

In this case, I was able to overcome the issue by enabling the `chain-stack-traces` flag in my test command - but I would imagine that this same error will occur if a user places a `print()` statement within a test.

**Comment by dorny** [comment]
Hi! Thanks for reporting the issue. I will fix it asap 👍
