### ISSUE TITLE
[Feature] Only Summary

### ISSUE THREAD

**Issue by workgroupengineering** [dorny/test-reporter#122]
Add option, which allows you to generate the summary only.

**Comment by dorny** [comment]
You can already use the following two options:
```yaml
list-tests: none           # disables listing of test cases - summary only
max-annotations: 0   # disables creation of code annotations with error details
```

Would this be sufficient for you?

**Comment by workgroupengineering** [comment]
I tryed solution you suggest but i don't have expect result.
