### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by LaPeste** [dorny/test-reporter#137]
I get `##[error]Cannot read property 'split' of undefined` when parsing test results with the java-junit reporter.
I looked at the code of the action and I understand that the error comes from [parsing the content of the file](https://github.com/dorny/test-reporter/blob/0d00bb14cb0cc2c9b8985df6e81dd333188224e1/src/main.ts#L152). Unfortunately, it's hard for me to pinpoint exactly where that's happening as there's no stacktrace and there's a huge try/catch in main.
I looked at the split calls used in the code, and I'd be tempted to say that the issue could be around parsing the stacktrace of the failing tests. However, the same test failures are happening in other platforms and there the action works just fine. I have this failure only in tests run on UWP.
[This](https://github.com/realm/realm-dotnet/runs/3496052733?check_suite_focus=true) is the test run where the issue appears.
I'm using version 1.5.0 because of the nice addition of `path-replace-backslashes`. If you believe that this error could have been introduced by this latest version, I can try to convert the backslashes myself and try 1.4.x .

**Comment by LaPeste** [comment]
I spent the time to go through it and the problem was in the fact that some of our test results had an empty `<failure message="  Expected: True&#xA;  But was:  False&#xA;"></failure>`. This is not accounted for by the action and so it crashes [here](https://github.com/dorny/test-reporter/blob/0d00bb14cb0cc2c9b8985df6e81dd333188224e1/src/parsers/java-junit/java-junit-parser.ts#L146). And a few other places where the a failure tag is always assumed to have content.
We're going to look into our test report to understand why we have some empty `<failure>`s, but I don't know if the failure tag should ever be expected to be null. If you think it should I can put up a PR. Let me know.

**Comment by JimLewis** [comment]
Great reporter, however, we are running into this issue too.   From the different reports I have seen, many reporters generate failure message of the form:
`<failure message=" Expected: True; But was: False;" /.>`

Is this not permitted here?  Do you have a schema for the XML you accept, expect, and/or test against?

**Comment by DanaGoyette** [comment]
For my uses (a customized version of mocha-junit-reporter to fix bugs with suite nesting), and when I tried using the jest-junit parser out of curiosity, it died with the same split error.  In my case, java-junit at least works.


 It would be far easier to debug if the tool logged what it was trying to parse when it died, and showed a backtrace!

**Comment by dkirrane** [comment]
hitting this with the below test results xml file `Error: Cannot read property 'split' of undefined`

    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Terratest Tests
        path: report.xml
        reporter: java-junit

report.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="1" failures="1" time="0.000" name="elvis">
		<properties>
			<property name="go.version" value="go1.17"></property>
		</properties>
		<testcase classname="elvis" name="[build failed]" time="0.000">
			<failure message="Failed" type=""></failure>
		</testcase>
	</testsuite>
</testsuites>
```
