### ISSUE TITLE
Exceeding the maximum annotations fails to produce a report

### ISSUE THREAD

**Issue by ejohnson-impinj** [dorny/test-reporter#143]
I'm using the test reporter to report test failures in workflows with test suites that often exceed 1000 tests, and it's somewhat common to have more than 50 tests fail in any given run. Per the specifications, the maximum number of detailed annotations permitted is 50 (with the default being 10), and it was my assumption that if the number of failed tests exceeded 50, 50 annotations would still be created and the remaining would simply be cut off.

However, what I'm seeing is that if the number of failed tests exceeds 50, the resulting report fails to generate and the test reporter produces an "Error: Invalid request" message.

Ideally, the maximum number of annotations would be raised beyond 50, however producing only 50 of the failing annotations would also be a sufficient, albeit less desirable solution.

Thank you!
![Screen Shot 2021-10-06 at 9 14 50 AM](https://user-images.githubusercontent.com/83662603/136244264-bd79673b-6124-4e46-b294-dea2ed4a71d0.png)

**Comment by coder5506** [comment]
I ran into this a few weeks ago.  The issue seemed to be that the rest report itself counts as an "annotation".  I think the limit comes from github, and not from the test reporter.  Anyway, I set "max-annotations: 49" on my run and that appeared to resolve the issue.

**Comment by ejohnson-impinj** [comment]
That works, thank you!
