### ISSUE TITLE
Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by KateHavrenko** [dorny/test-reporter#148]
Hi 
I have this issue at the moment
![image](https://user-images.githubusercontent.com/17851474/145786834-0830367f-737e-47d4-bc67-9130ebecf43f.png)
This is my workflow
![image](https://user-images.githubusercontent.com/17851474/145787365-390c7d8b-edbd-4aa4-a773-acdd30a22021.png)

**Comment by KateHavrenko** [comment]
Was an issue from my side

**Comment by andrewcourtice** [comment]
Hi @KateHavrenko - I'm having the same issue. What was your solution?

**Comment by tehKapa** [comment]
@pm-pp did you get any news about this?
