### ISSUE TITLE
Suppress "Processing test results from" log 

### ISSUE THREAD

**Issue by vasanthdharmaraj** [dorny/test-reporter#177]
Would it be possible to remove the log `Processing test results from... ` (https://github.com/dorny/test-reporter/blob/main/src/main.ts#L151) entries? We have a repo that generates over `3000` Junit reports. Scrolling through the actions' logs are tedious. 😢 

I would be happy to create a PR for it.

**Comment by geekiyer** [comment]
Agreed 💯. One has to scroll through all those lines to eventually get to the Report HTML url.
