### ISSUE TITLE
Is there maintained fork of this project ?

### ISSUE THREAD

**Issue by eshepelyuk** [dorny/test-reporter#183]
Hi all

Looks like the project is dead. Plz suggest alternatives with such pretty reports and multiple test result input formats.

If I am wrong and project is alive 
* why there is no reaction on PRs
* if I create a PR - is there any chance to get feedback in days,not monthes.

**Comment by toby-freemarket** [comment]
@dorny Is this project dead? 
If you don't have time at the moment I'm sure some people would be happy help out with the project

**Comment by dorny** [comment]
Hey @toby-freemarket,
I would not call it dead yet, but it has been in a coma for a while.
I'm really sorry about that. I started the project together with another one over a year ago. Back then I had some spare time. Unfortunately, past few months I had too much on me. I've been unsuccessfully trying to find some energy to sit down and work on it again. Well, I'm back from vacation now, so let's give it one more shot. I will check the PRs till the end of the week.

**Comment by toby-freemarket** [comment]
Please don't feel pressured and let us know if you need help. I run a couple open source projects too so I know the fun and pain 😄.

Your project is the best out of all the other test reporters for github actions.

Ďakujem!

**Comment by eshepelyuk** [comment]
There is a fork that has recent updates, jFYI

https://github.com/phoenix-actions/test-reporting

**Comment by flobernd** [comment]
> https://github.com/phoenix-actions/test-reporting

Looks like there is some useful stuff which could be merged upstream.

**Comment by dorny** [comment]
@flobernd Thanks I will try to check it out soon. 
Right now, I'm glad I've managed to update all the dependencies. I've run into some strange issues there.
But I still haven't got to all the issues and PRs...
