### ISSUE TITLE
Add HTML report url as output

### ISSUE THREAD

**Issue by BugHunt3rzzz** [dorny/test-reporter#253]
Hi there, it will be great if we add to action output `Check run HTML ` so it will be easier to put it for instance in slack message .
Currently I'm able to see it only inside step logs, which is not great 
<img width="1120" alt="image" src="https://github.com/dorny/test-reporter/assets/11724495/10981dcb-478c-45ea-a4d7-f5447610a4bb">

**Comment by yuvalprtn** [comment]
+1 on @BugHunt3rzzz request, the last ID is non trackable so having it in the output of the action will be great

**Comment by dgosantos89** [comment]
Just have one [PR](https://github.com/dorny/test-reporter/pull/242), but not reviewed yet 😞

**Comment by BugHunt3rzzz** [comment]
@yuvalprtn I was not able to extract thet url from log also, I guess it's not possible for action...

**Comment by j-catania** [comment]
Done in : https://github.com/dorny/test-reporter/pull/242
