### ISSUE TITLE
`swift-xunit` reporter invalid for the Action

### ISSUE THREAD

**Issue by Ast3r10n** [dorny/test-reporter#346]
The `swift-xunit` reporter seems not to be correctly recognised by the action.

![Screenshot 2023-12-22 at 17 29 58](https://github.com/dorny/test-reporter/assets/36516804/9dc21438-c648-4f90-9c9b-36b7b2b26fe5)

**Comment by jozefizso** [comment]
Please include more information about your setup so we can troubleshoot the issue.

**Comment by Ast3r10n** [comment]
I was trying to run this action on a Swift test workflow, but it simply wouldn't recognise the swift-xunit input as the chosen reporter. The attached screenshot was the failure log for this step:

- name: Test Reporter
  if: success() || failure()
  uses: dorny/test-reporter@v1.7.0
  with:
    name: Test Report
    path: Build/tuist_test_bundle_path$(current_date).xcresult
    reporter: swift-xunit

**Comment by jozefizso** [comment]
The `v1.7.0` does not include Swift reporter.

You must reference the action either my `main` branch or using the commit hash:

```
dorny/test-reporter@main
dorny/test-reporter@d9ef69ec3d6605cb603a1e7d58506dd1cbd8c166
```

**Comment by Ast3r10n** [comment]
Good to know! Though I would advise reflecting that in the documentation; it didn't appear to be stated as such.

**Comment by jozefizso** [comment]
This is standard behavior of GitHub Actions.

**Comment by Ast3r10n** [comment]
Never found an action pointing to main without a release to be honest. I was just pointing out it wasn't that obvious, based on most other actions I've used. No biggie anyway.
