### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'testsuite')

### ISSUE THREAD

**Issue by MrGadget1024** [dorny/test-reporter#348]
Workflow run: https://github.com/MirrorNetworking/Mirror/actions/runs/7330497702/job/19961702474

Workflow: https://github.com/MirrorNetworking/Mirror/blob/Test-CI-No-Merge/.github/workflows/RunUnityTests.yml

RunUnityTests is called from main.yml.

We are using `upload-artifact@v3` in case that matters.

**Make sure you're looking at the `Test-CI-No-Merge` branch.**
- There is one test that's intentionally made to fail in this branch.
- There are nearly 1100 tests in the repo.

Advice appreciated.

**Comment by lukasvida** [comment]
possible duplicate of #218

**Comment by jozefizso** [comment]
Hi @MrGadget1024 , the test run nor the workflow file is available anymore.

Please, include the name of the reported you are using, the type of test framework and its output format and a sample file which causes the error.

**Comment by MrGadget1024** [comment]
From Dec 2023? Of course they're long gone. We moved on to another solution.
