### ISSUE TITLE
Update to use node 20

### ISSUE THREAD

**Issue by dampcake** [dorny/test-reporter#365]
Node 16 is now deprecated by github, meaning builds using this action are getting warnings about using node 16. Please can it be updated to node 20.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by jozefizso** [comment]
The change is already implemented in the `main` branch and it waiting for release as part of the `1.8.0`


You must reference the action either my `main` branch or using the commit hash:

```
dorny/test-reporter@main
dorny/test-reporter@86a20101473378575dcbaa709a4f2b772001fbbb
```

**Comment by jozefizso** [comment]
Duplicate of https://github.com/dorny/test-reporter/pull/315
