### ISSUE TITLE
TEST SUITE FAILED TO RUN

### ISSUE THREAD

**Issue by wills-int** [dorny/test-reporter#411]
Is there any reason that I keep coming across this error when I run 'npm test'?

 ● Test suite failed to run
    Jest encountered an unexpected token
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
    By default "node_modules" folder is ignored by transformers.
    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation
    Details:

**Comment by jozefizso** [comment]
Where is this error coming from?

**Comment by wills-int** [comment]
> Where is this error coming from?

This error shows when I run 'npm test' from your branch and I can't get past it. and it shows 19 test failed out of 19. I can't get it to run a proper 'npm test'

**Comment by jozefizso** [comment]
I'm not sure which branch you are referring to, but the `main` branch can be built and teated correctly: https://github.com/dorny/test-reporter/actions/runs/8535201427

You would have to troubleshoot the issue on your machine.

**Comment by wills-int** [comment]
> I'm not sure which branch you are referring to, but the `main` branch can be built and teated correctly: https://github.com/dorny/test-reporter/actions/runs/8535201427
> 
> You would have to troubleshoot the issue on your machine.

Thank you. That was very helpful. Now can you help me with this last error when I'm trying to save and upload the file:

Warning: No files were found with the provided path: __tests__/__results__/*.xml. No artifacts will be uploaded.

**Comment by wills-int** [comment]
> I'm not sure which branch you are referring to, but the `main` branch can be built and teated correctly: https://github.com/dorny/test-reporter/actions/runs/8535201427
> 
> You would have to troubleshoot the issue on your machine.

Thank you, as that was an helpful link. That did the job
