### ISSUE TITLE
Repo tree not accesible

### ISSUE THREAD

**Issue by cvicenti-apr** [dorny/test-reporter#527]
https://github.com/dorny/test-reporter/tree/v1/ is currently returning 404.
Is this expected or perhaps there's an ongoing release?
Thanks

**Comment by cvicenti-apr** [comment]
Nevermind. It's back there again. Apologies

**Comment by pumalove** [comment]
Same issue here. 
Unable to resolve action `dorny/test-reporter@v1`, unable to find version `v1`

**Comment by jozefizso** [comment]
It was accidentally deleted when the #525 was merged. I've restored the `v1` branch.
