### ISSUE TITLE
`v1` branch no longer exists

### ISSUE THREAD

**Issue by jcorreia-forbesadvisor** [dorny/test-reporter#528]
## Describe the bug
Branch `v1` got deleted with #525 so actions pointing to it `uses: dorny/test-reporter@v1` are broken.

## To Reproduce
1. `uses: dorny/test-reporter@v1`
2. Error: Unable to resolve action `dorny/test-reporter@v1`, unable to find version `v1`

## Expected behavior
v1 to be available

**Comment by jozefizso** [comment]
The `v1` branch was restored.
