### ISSUE TITLE
Results table has horizontal scrollbar

### ISSUE THREAD

**Issue by MikeAndrews90** [dorny/test-reporter#59]
Hi we're trying out your test reporter for trx files, and the results table is quite thin with a horizontal scroll bar, see screenshot. I'd link you but it's a private repo.

We've got some pretty long test class names, so I imagine that's why. Is it possible to widen the table so there's no scrollbar?
![image](https://user-images.githubusercontent.com/29257758/108532222-89c33300-72cf-11eb-8e02-ac6c7762ad7e.png)

Thanks in advance.

**Comment by dorny** [comment]
Hello,

I'm aware of this issue, width for the table is ridiculously small. Unfortunately I can't change it.
Report is generated as markdown text and GitHub is fully in charge of rendering and styling.
It's not possible to display own html page or apply styling without going outside of GitHub.
Anyway it should rather wrap the text on next line than show a scrollbar. This works fine in Firefox but not in Chrome.
I will report it, hopefully they will fix it in the future.

For time being I could do few other things:
- trim beginning of names if they all starts with same prefix
- Add space after certain number of characters which will cause line to be wrapped also in Chrome

**Comment by dorny** [comment]
I reported the issue in GitHub support community forum:
[Check runs - problem with rendering of markdown tables](https://github.community/t/check-runs-problem-with-rendering-of-markdown-tables/162886)

**Comment by MikeAndrews90** [comment]
Hi,

Thanks for getting back to me - That makes sense. Hopefully they patch it!

**Comment by Jon889** [comment]
Could you make the results under the test name?
