### ISSUE TITLE
[dotnet-trx] Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by junhao2x** [dorny/test-reporter#82]
*Some logs:*

Run dorny/test-reporter@v1.3.0
  with:
    name: test-results
    reporter: dotnet-trx
    path: TestResults/*.trx
    list-suites: all
    list-tests: all
    max-annotations: 10
    fail-on-error: true
    token: ***
  env:
    NUGET: D:\Action-runner\intel-innersource\001\_work\_tool\nuget.exe\5.8.1\x64/nuget.exe
Action was triggered by pull_request: using SHA from head of source branch
Check runs will be created with SHA=30d3bbd87740e62cf5586edaa9a64fa0605ddf1c
Listing all files tracked by git
Found 964 files tracked by GitHub
Using test report parser 'dotnet-trx'
Creating test report test-results
Error: Cannot read property 'match' of undefined

----------------------------------------------------------------------------------------------------------------------------------------------

*And this is the summary of the test result (since I know some _Marketplace Actions_ need users to specify the upper bound of the number of passed/failed cases) : *

Test Run Failed.
Total tests: 139
     Passed: 65
     Failed: 71
    Skipped: 3
 Total time: 2.0720 Minutes

----------------------------------------------------------------------------------------------------------------------------------------------

I was running an old project, and I know it uses a lot of things from pre-2015. So the reason may be that something is too old to be compatible with your stuffs. Let me know what you need from me, or can you repro the issue.

Thanks,

Junhao Zhang "Freddie"

**Comment by dorny** [comment]
@junhao2x Thanks for reporting the issue.
Looking at the code I guess that `duration` attribute of `<UnitTestResult>` was not set.
To be sure, would be possible to upload here the `*.trx` file ?

**Comment by junhao2x** [comment]
Here you are. I have to put it into a zip otherwise GitHub popes me error says they don't support that format (*.trx)
[trx.zip](https://github.com/dorny/test-reporter/files/6192812/trx.zip)
